### ISSUE TITLE
为什么选择时间小时分钟时，是上下点击选择的样式 

### ISSUE THREAD

**Issue by a315103062** [mayufo/vue-date-time-m#1]
为什么选择时间时是上下点击选择的样式 而不是示例里的滚轮的样式

**Comment by mayufo** [comment]
请删除你目前的依赖，安装最新的版本

**Comment by a315103062** [comment]
我现在的版本是"vue-date-time-m": "^1.0.23"

**Comment by mayufo** [comment]
最新的是 1.0.24

**Comment by a315103062** [comment]
![tim 20180828113153](https://user-images.githubusercontent.com/36907027/44699281-0fc2e200-aab6-11e8-93cc-33a630cb2420.png)
还没有这个版本的

**Comment by mayufo** [comment]
![image](https://user-images.githubusercontent.com/3355053/44699431-c1faa980-aab6-11e8-946a-e1dff283f41f.png)

![image](https://user-images.githubusercontent.com/3355053/44699438-c9ba4e00-aab6-11e8-9f69-2d620092f5e0.png)

btw: 项目名字最好不要中文命名

**Comment by a315103062** [comment]
解决了 淘宝源还不是最新的 换了下就好了
