### ISSUE TITLE
明确的许可信息

### ISSUE THREAD

**Issue by adah1972** [mayufo/vue-date-time-m#10]
能不能在代码里加入明确的许可信息，并在 NPM 页面上也明确声明一下？

MIT 许可似乎是 NPM 组件中最流行的许可。如果不确定的话，用这个就挺好？可以在项目根目录下加一个 LICENSE 文件，里面贴入 MIT 许可的内容（版权所有人/时间需要根据项目情况修改）。

示例：

https://github.com/wandergis/coordtransform/blob/master/LICENSE

**Comment by mayufo** [comment]
非常感谢您的提议 我稍后加上

**Comment by adah1972** [comment]
另外提个建议，您可以在加上许可之后再关闭issue。这样的话，既方便提醒您自己，也方便我跟踪这个问题——关闭说明问题已经解决。现在我只能通过查看项目的方式来检查这个问题了……

**Comment by mayufo** [comment]
好的  好的 虚心接受！

**Comment by mayufo** [comment]
要不你再开个issue

**Comment by adah1972** [comment]
哈哈，你可以 reopen issue 吧？或者你把许可贴了，那就本来 issue 就可以关闭了。
