### ISSUE TITLE
type类型是月份的时候可以把年带上吗

### ISSUE THREAD

**Issue by linjinglinjie** [mayufo/vue-date-time-m#13]
type类型是月份的时候可以把年带上吗

**Comment by mayufo** [comment]
已经增加`type="yearMonth"` 可以年月

**Comment by linjinglinjie** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"mayufo"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月28日(星期一) 下午3:19
收件人:&nbsp;"mayufo/vue-date-time-m"<vue-date-time-m@noreply.github.com&gt;;
抄送:&nbsp;"蔺婧"<729181398@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mayufo/vue-date-time-m] type类型是月份的时候可以把年带上吗 (#13)




已经增加type="yearMonth" 可以年月
