### ISSUE TITLE
iphone 上 我设置min之后不起效果，且上一个月功能失效，安卓没问题

### ISSUE THREAD

**Issue by duminghong** [mayufo/vue-date-time-m#3]
安卓上，min之前都是灰色，功能一切正常
ios未变色，之前的日期依然可选，且选到下一个月，再次选择切换不回上一个月，按钮失效
min是动态设置的
```
<!-- html -->
<date-time ref="startTime" @confirm="startTimeSelect" format="yyyy-MM-dd hh:mm" color="#00BED1" :min="currentTime">
    <div class="dataTimeBtn" slot="prevMonth">-</div>
    <div class="dataTimeBtn" slot="nextMonth">+</div>
</date-time>
<date-time ref="endTime" @confirm="endTimeSelect" format="yyyy-MM-dd hh:mm" color="#00BED1" :min="startTime">
    <div class="dataTimeBtn" slot="prevMonth">-</div>
    <div class="dataTimeBtn" slot="nextMonth">+</div>
</date-time>
```
以下是js:
```
import dayjs from 'dayjs'
......
{
    data(){
        return{
            currentTime: '',
            startTime:'',
            endTime:'',
            ......
        }
    },
    methods: {
        // 展示日期组件
        timeShow (inx) {
            if(inx==1){
                this.currentTime = dayjs().format('YYYY-MM-DD HH:mm');
                this.$refs.startTime.show()
            }else{
                this.$refs.endTime.show()
            }
        },
        // 日期组件回调
        startTimeSelect(val) {
            this.startTime = val;
            if(dayjs(this.startTime).isAfter(dayjs(this.endTime))){
                this.endTime='';
            }
        },
        endTimeSelect(val) {
            this.endTime = val;
        },
    }
}
```

**Comment by mayufo** [comment]
不好意思 回复晚了 
this.currentTime = dayjs().format('YYYY-MM-DD HH:mm').toString() 试一下

**Comment by mayufo** [comment]
> 安卓上，min之前都是灰色，功能一切正常
> ios未变色，之前的日期依然可选，且选到下一个月，再次选择切换不回上一个月，按钮失效
> min是动态设置的
> 
> ```
> 
> <date-time ref="startTime" @confirm="startTimeSelect" format="yyyy-MM-dd hh:mm" color="#00BED1" :min="currentTime">
>     <div class="dataTimeBtn" slot="prevMonth">-</div>
>     <div class="dataTimeBtn" slot="nextMonth">+</div>
> </date-time>
> <date-time ref="endTime" @confirm="endTimeSelect" format="yyyy-MM-dd hh:mm" color="#00BED1" :min="startTime">
>     <div class="dataTimeBtn" slot="prevMonth">-</div>
>     <div class="dataTimeBtn" slot="nextMonth">+</div>
> </date-time>
> ```
> 以下是js:
> 
> ```
> import dayjs from 'dayjs'
> ......
> {
>     data(){
>         return{
>             currentTime: '',
>             startTime:'',
>             endTime:'',
>             ......
>         }
>     },
>     methods: {
>         // 展示日期组件
>         timeShow (inx) {
>             if(inx==1){
>                 this.currentTime = dayjs().format('YYYY-MM-DD HH:mm');
>                 this.$refs.startTime.show()
>             }else{
>                 this.$refs.endTime.show()
>             }
>         },
>         // 日期组件回调
>         startTimeSelect(val) {
>             this.startTime = val;
>             if(dayjs(this.startTime).isAfter(dayjs(this.endTime))){
>                 this.endTime='';
>             }
>         },
>         endTimeSelect(val) {
>             this.endTime = val;
>         },
>     }
> }
> ```

不好意思 回复晚了
this.currentTime = dayjs().format('YYYY-MM-DD HH:mm').toString() 试一下
