### ISSUE TITLE
type改变, 只显示年月日时，选择月后，关闭按钮不起作用

### ISSUE THREAD

**Issue by xiaobo12138** [mayufo/vue-date-time-m#6]
![0st 2rs4q4 s 5m3x_aom](https://user-images.githubusercontent.com/38715384/51593810-f8393980-1f2d-11e9-9e3b-1685c9c3a725.png)
先谢过开发者，辛苦了，
type改变, 只显示年月日时，选择月后，关闭按钮不起作用

**Comment by xiaobo12138** [comment]
选择年，月之后，关闭按钮都不起作用

**Comment by mayufo** [comment]
感谢你的反馈 我这就修改..

**Comment by mayufo** [comment]
已经解决

**Comment by Mradxz** [comment]
我遇到的同样的问题
