### ISSUE TITLE
english version

### ISSUE THREAD

**Issue by qqjiandj123** [mayufo/vue-date-time-m#9]
博主能提供一个中英文切换的功能吗？ 感谢

**Comment by mayufo** [comment]
就三个按钮的文字 需要改变吗？

**Comment by qqjiandj123** [comment]
除了三个按钮 还有 中间的月需要换成英文

**Comment by qqjiandj123** [comment]
其他的就没有了

**Comment by qqjiandj123** [comment]
其实中间部分最好能显示英文版的月 比如 January February March ... 12个月

**Comment by qqjiandj123** [comment]
博主在吗？ 能刚忙修改一下吗！  谢谢啦

**Comment by mayufo** [comment]
最近项目比较忙 你可以fork 一下自己改下

**Comment by qqjiandj123** [comment]
博主! run build 为什么不能生成 vue-date-time-m.js 和 vue-date-time-m-browser.js文件啊

**Comment by mayufo** [comment]
请看 package.json
